# Generated by Django 3.2.9 on 2021-12-03 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ttt.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=12, unique=True)),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_1', to=settings.AUTH_USER_MODEL)),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('player_1', 'player_2')},
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('result', models.CharField(max_length=1, null=True, validators=[ttt.models.validate_result])),
                ('circle_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circle_player', to=settings.AUTH_USER_MODEL)),
                ('cross_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cross_player', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ttt.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_nr', models.IntegerField(validators=[ttt.models.validate_board])),
                ('position', models.IntegerField(validators=[ttt.models.validate_position])),
                ('value', models.CharField(max_length=1, validators=[ttt.models.validate_result])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ttt.game')),
            ],
            options={
                'unique_together': {('game', 'board_nr', 'position')},
            },
        ),
    ]
