# Generated by Django 3.2.9 on 2021-11-15 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ttt.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=12, unique=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=12, unique=True)),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_1', to=settings.AUTH_USER_MODEL)),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('circle_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circle_player', to=settings.AUTH_USER_MODEL)),
                ('cross_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cross_player', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ttt.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(validators=[ttt.validators.validate_position])),
                ('symbol', models.CharField(max_length=1, validators=[ttt.validators.validate_symbol])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ttt.game')),
            ],
            options={
                'unique_together': {('game', 'position')},
            },
        ),
    ]
